// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function ApproveAccessRequest(arg1:number,arg2:string):Promise<void>;

export function CreateInvite(arg1:number,arg2:any,arg3:string):Promise<services.InviteInfo>;

export function GetAccessRequests(arg1:number):Promise<Array<services.AccessRequestInfo>>;

export function GetAuditLog(arg1:number,arg2:string,arg3:number):Promise<services.AuditPage>;

export function GetInvites(arg1:number):Promise<Array<services.InviteInfo>>;

export function RejectAccessRequest(arg1:number,arg2:string):Promise<void>;

export function RevokeInvite(arg1:number,arg2:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetServerIcon(arg1:number,arg2:string):Promise<void>;

export function UpdateServer(arg1:number,arg2:string,arg3:string):Promise<void>;
