// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveAccessRequest(arg1, arg2) {
  return window['go']['services']['AdminService']['ApproveAccessRequest'](arg1, arg2);
}

export function CreateInvite(arg1, arg2, arg3) {
  return window['go']['services']['AdminService']['CreateInvite'](arg1, arg2, arg3);
}

export function GetAccessRequests(arg1) {
  return window['go']['services']['AdminService']['GetAccessRequests'](arg1);
}

export function GetAuditLog(arg1, arg2, arg3) {
  return window['go']['services']['AdminService']['GetAuditLog'](arg1, arg2, arg3);
}

export function GetInvites(arg1) {
  return window['go']['services']['AdminService']['GetInvites'](arg1);
}

export function RejectAccessRequest(arg1, arg2) {
  return window['go']['services']['AdminService']['RejectAccessRequest'](arg1, arg2);
}

export function RevokeInvite(arg1, arg2) {
  return window['go']['services']['AdminService']['RevokeInvite'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['services']['AdminService']['SetContext'](arg1);
}

export function SetServerIcon(arg1, arg2) {
  return window['go']['services']['AdminService']['SetServerIcon'](arg1, arg2);
}

export function UpdateServer(arg1, arg2, arg3) {
  return window['go']['services']['AdminService']['UpdateServer'](arg1, arg2, arg3);
}
