// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function GetState():Promise<services.AppState>;

export function Initialize():Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Shutdown():Promise<void>;
