// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetState() {
  return window['go']['services']['AppService']['GetState']();
}

export function Initialize() {
  return window['go']['services']['AppService']['Initialize']();
}

export function SetContext(arg1) {
  return window['go']['services']['AppService']['SetContext'](arg1);
}

export function Shutdown() {
  return window['go']['services']['AppService']['Shutdown']();
}
