// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function CreateCategory(arg1:number,arg2:string,arg3:string):Promise<services.Category>;

export function CreateChannel(arg1:number,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<services.Channel>;

export function DeleteCategory(arg1:number,arg2:string):Promise<void>;

export function DeleteChannel(arg1:number,arg2:string):Promise<void>;

export function GetCategories(arg1:number):Promise<Array<services.Category>>;

export function GetChannels(arg1:number,arg2:string):Promise<Array<services.Channel>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateCategory(arg1:number,arg2:string,arg3:string,arg4:number):Promise<void>;

export function UpdateChannel(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number,arg6:Array<string>):Promise<void>;
