// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCategory(arg1, arg2, arg3) {
  return window['go']['services']['ChannelService']['CreateCategory'](arg1, arg2, arg3);
}

export function CreateChannel(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['ChannelService']['CreateChannel'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteCategory(arg1, arg2) {
  return window['go']['services']['ChannelService']['DeleteCategory'](arg1, arg2);
}

export function DeleteChannel(arg1, arg2) {
  return window['go']['services']['ChannelService']['DeleteChannel'](arg1, arg2);
}

export function GetCategories(arg1) {
  return window['go']['services']['ChannelService']['GetCategories'](arg1);
}

export function GetChannels(arg1, arg2) {
  return window['go']['services']['ChannelService']['GetChannels'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['services']['ChannelService']['SetContext'](arg1);
}

export function UpdateCategory(arg1, arg2, arg3, arg4) {
  return window['go']['services']['ChannelService']['UpdateCategory'](arg1, arg2, arg3, arg4);
}

export function UpdateChannel(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['services']['ChannelService']['UpdateChannel'](arg1, arg2, arg3, arg4, arg5, arg6);
}
