// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptCall(arg1, arg2) {
  return window['go']['services']['DMService']['AcceptCall'](arg1, arg2);
}

export function AddMember(arg1, arg2, arg3) {
  return window['go']['services']['DMService']['AddMember'](arg1, arg2, arg3);
}

export function CreateDM(arg1, arg2) {
  return window['go']['services']['DMService']['CreateDM'](arg1, arg2);
}

export function GetConversations(arg1) {
  return window['go']['services']['DMService']['GetConversations'](arg1);
}

export function GetHistory(arg1, arg2, arg3, arg4) {
  return window['go']['services']['DMService']['GetHistory'](arg1, arg2, arg3, arg4);
}

export function LeaveCall() {
  return window['go']['services']['DMService']['LeaveCall']();
}

export function LeaveConversation(arg1, arg2) {
  return window['go']['services']['DMService']['LeaveConversation'](arg1, arg2);
}

export function RejectCall(arg1, arg2) {
  return window['go']['services']['DMService']['RejectCall'](arg1, arg2);
}

export function RemoveMember(arg1, arg2, arg3) {
  return window['go']['services']['DMService']['RemoveMember'](arg1, arg2, arg3);
}

export function Send(arg1, arg2, arg3) {
  return window['go']['services']['DMService']['Send'](arg1, arg2, arg3);
}

export function SetContext(arg1) {
  return window['go']['services']['DMService']['SetContext'](arg1);
}

export function StartCall(arg1, arg2) {
  return window['go']['services']['DMService']['StartCall'](arg1, arg2);
}
