// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function AcceptCall(arg1:number,arg2:string):Promise<void>;

export function AddMember(arg1:number,arg2:string,arg3:string):Promise<void>;

export function CreateDM(arg1:number,arg2:Array<string>):Promise<services.DMConversationInfo>;

export function GetConversations(arg1:number):Promise<Array<services.DMConversationInfo>>;

export function GetHistory(arg1:number,arg2:string,arg3:string,arg4:number):Promise<services.DMMessagePage>;

export function LeaveCall():Promise<void>;

export function LeaveConversation(arg1:number,arg2:string):Promise<void>;

export function RejectCall(arg1:number,arg2:string):Promise<void>;

export function RemoveMember(arg1:number,arg2:string,arg3:string):Promise<void>;

export function Send(arg1:number,arg2:string,arg3:string):Promise<services.DMMessageOut>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartCall(arg1:number,arg2:string):Promise<void>;
