// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {services} from '../models';

export function Download(arg1:number,arg2:string,arg3:string):Promise<void>;

export function PickAndDownload(arg1:number,arg2:string):Promise<void>;

export function PickFile():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Upload(arg1:number,arg2:string,arg3:string):Promise<services.FileInfo>;
