// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Download(arg1, arg2, arg3) {
  return window['go']['services']['FileService']['Download'](arg1, arg2, arg3);
}

export function PickAndDownload(arg1, arg2) {
  return window['go']['services']['FileService']['PickAndDownload'](arg1, arg2);
}

export function PickFile() {
  return window['go']['services']['FileService']['PickFile']();
}

export function SetContext(arg1) {
  return window['go']['services']['FileService']['SetContext'](arg1);
}

export function Upload(arg1, arg2, arg3) {
  return window['go']['services']['FileService']['Upload'](arg1, arg2, arg3);
}
