// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1, arg2) {
  return window['go']['services']['MessageService']['Delete'](arg1, arg2);
}

export function Edit(arg1, arg2, arg3) {
  return window['go']['services']['MessageService']['Edit'](arg1, arg2, arg3);
}

export function GetHistory(arg1, arg2, arg3, arg4) {
  return window['go']['services']['MessageService']['GetHistory'](arg1, arg2, arg3, arg4);
}

export function Search(arg1, arg2) {
  return window['go']['services']['MessageService']['Search'](arg1, arg2);
}

export function Send(arg1, arg2, arg3, arg4) {
  return window['go']['services']['MessageService']['Send'](arg1, arg2, arg3, arg4);
}

export function SetContext(arg1) {
  return window['go']['services']['MessageService']['SetContext'](arg1);
}
