// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function Delete(arg1:number,arg2:string):Promise<void>;

export function Edit(arg1:number,arg2:string,arg3:string):Promise<void>;

export function GetHistory(arg1:number,arg2:string,arg3:string,arg4:number):Promise<services.MessagePage>;

export function Search(arg1:number,arg2:services.MessageSearchParams):Promise<services.SearchResult>;

export function Send(arg1:number,arg2:string,arg3:string,arg4:Array<string>):Promise<services.Message>;

export function SetContext(arg1:context.Context):Promise<void>;
