// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function ExportIdentity(arg1:string):Promise<void>;

export function GetAvatar():Promise<string>;

export function GetProfile():Promise<services.Profile>;

export function GetPublicKey():Promise<string>;

export function ImportIdentity(arg1:string):Promise<void>;

export function PreviewAvatar(arg1:string):Promise<string>;

export function ReadFileAsDataURL(arg1:string):Promise<string>;

export function RemoveAvatar():Promise<void>;

export function SetAvatar(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateProfile(arg1:string,arg2:string,arg3:string):Promise<void>;
