// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportIdentity(arg1) {
  return window['go']['services']['ProfileService']['ExportIdentity'](arg1);
}

export function GetAvatar() {
  return window['go']['services']['ProfileService']['GetAvatar']();
}

export function GetProfile() {
  return window['go']['services']['ProfileService']['GetProfile']();
}

export function GetPublicKey() {
  return window['go']['services']['ProfileService']['GetPublicKey']();
}

export function ImportIdentity(arg1) {
  return window['go']['services']['ProfileService']['ImportIdentity'](arg1);
}

export function PreviewAvatar(arg1) {
  return window['go']['services']['ProfileService']['PreviewAvatar'](arg1);
}

export function ReadFileAsDataURL(arg1) {
  return window['go']['services']['ProfileService']['ReadFileAsDataURL'](arg1);
}

export function RemoveAvatar() {
  return window['go']['services']['ProfileService']['RemoveAvatar']();
}

export function SetAvatar(arg1) {
  return window['go']['services']['ProfileService']['SetAvatar'](arg1);
}

export function SetContext(arg1) {
  return window['go']['services']['ProfileService']['SetContext'](arg1);
}

export function UpdateProfile(arg1, arg2, arg3) {
  return window['go']['services']['ProfileService']['UpdateProfile'](arg1, arg2, arg3);
}
