// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssignRole(arg1, arg2, arg3) {
  return window['go']['services']['RoleService']['AssignRole'](arg1, arg2, arg3);
}

export function CreateRole(arg1, arg2, arg3, arg4) {
  return window['go']['services']['RoleService']['CreateRole'](arg1, arg2, arg3, arg4);
}

export function DeleteRole(arg1, arg2) {
  return window['go']['services']['RoleService']['DeleteRole'](arg1, arg2);
}

export function GetRoles(arg1) {
  return window['go']['services']['RoleService']['GetRoles'](arg1);
}

export function RevokeRole(arg1, arg2, arg3) {
  return window['go']['services']['RoleService']['RevokeRole'](arg1, arg2, arg3);
}

export function SetContext(arg1) {
  return window['go']['services']['RoleService']['SetContext'](arg1);
}

export function UpdateRole(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['services']['RoleService']['UpdateRole'](arg1, arg2, arg3, arg4, arg5, arg6);
}
