// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function AssignRole(arg1:number,arg2:string,arg3:string):Promise<void>;

export function CreateRole(arg1:number,arg2:string,arg3:string,arg4:number):Promise<services.Role>;

export function DeleteRole(arg1:number,arg2:string):Promise<void>;

export function GetRoles(arg1:number):Promise<Array<services.Role>>;

export function RevokeRole(arg1:number,arg2:string,arg3:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateRole(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<void>;
