// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAccessRequest() {
  return window['go']['services']['ServerService']['CancelAccessRequest']();
}

export function Connect(arg1) {
  return window['go']['services']['ServerService']['Connect'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['services']['ServerService']['Disconnect'](arg1);
}

export function GetRelayServers() {
  return window['go']['services']['ServerService']['GetRelayServers']();
}

export function GetServerInfo(arg1) {
  return window['go']['services']['ServerService']['GetServerInfo'](arg1);
}

export function GetServers() {
  return window['go']['services']['ServerService']['GetServers']();
}

export function LeaveServer(arg1, arg2) {
  return window['go']['services']['ServerService']['LeaveServer'](arg1, arg2);
}

export function Reconnect(arg1) {
  return window['go']['services']['ServerService']['Reconnect'](arg1);
}

export function RejectTrust() {
  return window['go']['services']['ServerService']['RejectTrust']();
}

export function RemoveRelay(arg1) {
  return window['go']['services']['ServerService']['RemoveRelay'](arg1);
}

export function SetContext(arg1) {
  return window['go']['services']['ServerService']['SetContext'](arg1);
}

export function SetFocusedServer(arg1) {
  return window['go']['services']['ServerService']['SetFocusedServer'](arg1);
}

export function SubmitAccessRequest(arg1) {
  return window['go']['services']['ServerService']['SubmitAccessRequest'](arg1);
}

export function TrustAndAuth(arg1) {
  return window['go']['services']['ServerService']['TrustAndAuth'](arg1);
}
