// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function CancelAccessRequest():Promise<void>;

export function Connect(arg1:string):Promise<services.ServerHello>;

export function Disconnect(arg1:number):Promise<void>;

export function GetRelayServers():Promise<Array<services.ServerEntry>>;

export function GetServerInfo(arg1:number):Promise<services.ServerInfo>;

export function GetServers():Promise<Array<services.ServerEntry>>;

export function LeaveServer(arg1:number,arg2:string):Promise<void>;

export function Reconnect(arg1:number):Promise<void>;

export function RejectTrust():Promise<void>;

export function RemoveRelay(arg1:number):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetFocusedServer(arg1:number):Promise<void>;

export function SubmitAccessRequest(arg1:string):Promise<void>;

export function TrustAndAuth(arg1:string):Promise<void>;
