// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function GetAppSettings():Promise<services.AppSettings>;

export function GetServerSettings(arg1:number):Promise<services.PerServerSettings>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateAppSettings(arg1:services.AppSettings):Promise<void>;

export function UpdateServerSettings(arg1:number,arg2:services.PerServerSettings):Promise<void>;
