// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppSettings() {
  return window['go']['services']['SettingsService']['GetAppSettings']();
}

export function GetServerSettings(arg1) {
  return window['go']['services']['SettingsService']['GetServerSettings'](arg1);
}

export function SetContext(arg1) {
  return window['go']['services']['SettingsService']['SetContext'](arg1);
}

export function UpdateAppSettings(arg1) {
  return window['go']['services']['SettingsService']['UpdateAppSettings'](arg1);
}

export function UpdateServerSettings(arg1, arg2) {
  return window['go']['services']['SettingsService']['UpdateServerSettings'](arg1, arg2);
}
