// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function BanUser(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function GetBans(arg1:number):Promise<Array<services.Ban>>;

export function GetUser(arg1:number,arg2:string):Promise<services.User>;

export function GetUsers(arg1:number):Promise<Array<services.User>>;

export function KickUser(arg1:number,arg2:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetStatus(arg1:number,arg2:string):Promise<void>;

export function SetStatusAll(arg1:string):Promise<void>;

export function UnbanUser(arg1:number,arg2:string):Promise<void>;
