// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BanUser(arg1, arg2, arg3, arg4) {
  return window['go']['services']['UserService']['BanUser'](arg1, arg2, arg3, arg4);
}

export function GetBans(arg1) {
  return window['go']['services']['UserService']['GetBans'](arg1);
}

export function GetUser(arg1, arg2) {
  return window['go']['services']['UserService']['GetUser'](arg1, arg2);
}

export function GetUsers(arg1) {
  return window['go']['services']['UserService']['GetUsers'](arg1);
}

export function KickUser(arg1, arg2) {
  return window['go']['services']['UserService']['KickUser'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['services']['UserService']['SetContext'](arg1);
}

export function SetStatus(arg1, arg2) {
  return window['go']['services']['UserService']['SetStatus'](arg1, arg2);
}

export function SetStatusAll(arg1) {
  return window['go']['services']['UserService']['SetStatusAll'](arg1);
}

export function UnbanUser(arg1, arg2) {
  return window['go']['services']['UserService']['UnbanUser'](arg1, arg2);
}
