// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {audio} from '../models';
import {services} from '../models';
import {context} from '../models';

export function GetInputDevices():Promise<Array<audio.AudioDevice>>;

export function GetOutputDevices():Promise<Array<audio.AudioDevice>>;

export function GetVolume():Promise<number>;

export function JoinChannel(arg1:number,arg2:string):Promise<Array<services.VoiceParticipant>>;

export function LeaveChannel():Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetDeafened(arg1:boolean):Promise<void>;

export function SetInputDevice(arg1:string):Promise<void>;

export function SetMuted(arg1:boolean):Promise<void>;

export function SetOutputDevice(arg1:string):Promise<void>;

export function SetVolume(arg1:number):Promise<void>;
