// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInputDevices() {
  return window['go']['services']['VoiceService']['GetInputDevices']();
}

export function GetOutputDevices() {
  return window['go']['services']['VoiceService']['GetOutputDevices']();
}

export function GetVolume() {
  return window['go']['services']['VoiceService']['GetVolume']();
}

export function JoinChannel(arg1, arg2) {
  return window['go']['services']['VoiceService']['JoinChannel'](arg1, arg2);
}

export function LeaveChannel() {
  return window['go']['services']['VoiceService']['LeaveChannel']();
}

export function SetContext(arg1) {
  return window['go']['services']['VoiceService']['SetContext'](arg1);
}

export function SetDeafened(arg1) {
  return window['go']['services']['VoiceService']['SetDeafened'](arg1);
}

export function SetInputDevice(arg1) {
  return window['go']['services']['VoiceService']['SetInputDevice'](arg1);
}

export function SetMuted(arg1) {
  return window['go']['services']['VoiceService']['SetMuted'](arg1);
}

export function SetOutputDevice(arg1) {
  return window['go']['services']['VoiceService']['SetOutputDevice'](arg1);
}

export function SetVolume(arg1) {
  return window['go']['services']['VoiceService']['SetVolume'](arg1);
}
